Feature/2 init monorepo
ga0hyeon/CN-SIDE-1 pull request #8
Opened 2023-03-28 01:48 UTC by sprinter707

## 📖 스토리
https://github.com/ga0hyeon/CN-SIDE-1/issues/2

## 💻 작업내용
- lerna를 이용한 monorepo 구성
- main-component 패키지 생성(repo)
- storybook 적용

## 🧐 테스트 

> npx lerna bootstrap --hoist
> yarn build
or
> cd packages/main-component
> yarn dev

## ✨ 참고내용 / 관련 MR

2023-03-28 13:06 UTC, yunju-choi commented
node 18.x.x 버전을 이용하니까 yarn storybook 수행했을때 아래 에러가 나서 16대로 내리니까 잘 됩니다👍👍

error:0308010C:digital envelope routines::unsupported

2023-03-30 03:06 UTC, sprinter707 commented
> node 18.x.x 버전을 이용하니까 yarn storybook 수행했을때 아래 에러가 나서 16대로 내리니까 잘 됩니다👍👍
> 
> error:0308010C:digital envelope routines::unsupported

제 개발환경을 확인해보니 노드 18.2.0 을 사용하고 있네요..

2023-03-30 04:12 UTC, yunju-choi commented
아 저 안됐던 버전이 18.13.0 버전이었습니다!! 18.2 >> 18.13 이 되는 중에 어느 버전부터인가 안 됐을 수 있겠네요

2023-03-30 05:20 UTC, ga0hyeon commented
![image](https://user-images.githubusercontent.com/23169601/228737043-9122f665-a9d9-402c-9b54-cd38004d23d8.png)
제 리뷰 왜 안보이는 겁니까

2023-03-30 05:22 UTC, ga0hyeon commented
https://velog.io/@gth1123/github-review-pending <-- 여기 나와잇어요 멍청..

2023-03-30 05:23 UTC, ga0hyeon requested changes
리뷰를 다 하고 나면 submit을 해야한답니다 ㅠㅠ

2023-03-30 05:23 UTC, ga0hyeon commented on package-lock.json
패키지 관리자는 yarn 이나 bun 어떠신가요?

2023-03-30 05:25 UTC, sprinter707 commented on package-lock.json
lerna에서 npm 이아닌 yarn이 사용가능한지 확인해볼께요

2023-03-30 05:32 UTC, sprinter707 commented on package-lock.json
yarn으로 수정했습니다.

그런데 lerna에서 hoist 기능이 yarn에서도 잘되는지 확인이 필요하긴 할거 같아요.
```
$ npx lerna bootstrap --hoist
lerna notice cli v6.6.1
lerna ERR! EWORKSPACES --hoist is not supported with --npm-client=yarn, use yarn workspaces instead
lerna ERR! EWORKSPACES A guide is available at https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/
```

2023-03-30 06:14 UTC, ga0hyeon approved these changes

2023-03-30 06:14 UTC, ga0hyeon commented on README.md
> +# CN-SIDE-01
yo

2023-03-30 07:22 UTC, yunju-choi commented on README.md
> +# CN-SIDE-01
yo!

2023-04-04 12:30 UTC, yunju-choi approved these changes
제스퍼님👍👍👍

2023-04-04 12:35 UTC, sprinter707 commented
> > node 18.x.x 버전을 이용하니까 yarn storybook 수행했을때 아래 에러가 나서 16대로 내리니까 잘 됩니다👍👍
> > error:0308010C:digital envelope routines::unsupported
> 
> 제 개발환경을 확인해보니 노드 18.2.0 을 사용하고 있네요.. ❯ node --version v18.2.0 ❯ npm -v 8.9.0
> 
> 원인을 더 자세히 확인해봐야겠어요...ㅠㅠ

검색해보니 해당 오류의 원인은 2가지라고 하네요
1. Node JS의 LTS 버전 사용하지 않음
2. React 스크립트 버전이 5 이하

우리는 react-script 가 포함되지 않았고,,, nodeJS 의 문제로 보여지네요...
(LTS 버전에만 따로 들어가있는 환경변수가 있는것인지... 알수없네요...)
일반적인 경우의 에러는 아닌것으로 보여집니다... ㅠㅠ

2023-04-04 12:36 UTC, merged